### ISSUE TITLE
Cleanup docs.

### ISSUE THREAD

**Issue by crertel** [crertel/graphmath#15]
So, the documentation for the modules is a little hard to navigate.

Also, the description for the library as it appears in Hex is a bit off.

Lastly, thanks to @RobertDober's help, we have a chance to update to a new version of ex_doc and to acknowledge his help as a contributor. :)

**Comment by crertel** [comment]
This work is being done in branch `15-cleanup-docs`.

**Comment by RobertDober** [comment]
Thank you @crertel but it was no big deal. However, as you mentioned above, maybe you could also kindly ask about the progress of this: https://github.com/elixir-lang/ex_doc/pull/565 as it is blocking the filename and line number feature.

**Comment by crertel** [comment]
Closing out old issues. Looks like that other issue in ex_doc got address. :)

**Comment by RobertDober** [comment]
all things come to the patient ;)
